CREATE TABLE specialization (
    specialization_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    specialization_name text NOT NULL
);

CREATE TABLE employee
(
    employee_id   integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    employee_name text not null
);

CREATE TABLE area
(
    area_id   integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    area_name text not null
);

CREATE TABLE employer
(
    employer_id   integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    employer_name text not null

);

CREATE TABLE resume (
    resume_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id  integer not null references employee (employee_id),
    title text NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,

    first_name text NOT NULL,
    last_name text NOT NULL,
    middle_name text,
    phone_number varchar(12),

    compensation_from integer,
    compensation_to   integer,

    region_id integer NOT NULL,
    FOREIGN KEY (region_id) REFERENCES area(area_id),
    specialization_id integer NOT NULL,
    FOREIGN KEY (specialization_id) REFERENCES specialization(specialization_id)
);

CREATE TABLE vacancy (
    vacancy_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_title text NOT NULL,
    employer_id integer NOT NULL,
    FOREIGN KEY (employer_id) REFERENCES employer (employer_id),
    specialization_id integer NOT NULL,
    FOREIGN KEY (specialization_id) REFERENCES specialization (specialization_id),
    hours_per_week integer,
    compensation_from integer,
    compensation_to integer,
    openned_at timestamp DEFAULT CURRENT_TIMESTAMP,

    area_id integer NOT NULL,
    FOREIGN KEY (area_id) REFERENCES area (area_id),
    description  text
);

CREATE TABLE response(
    response_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    vacancy_id integer NOT NULL,
    FOREIGN KEY (vacancy_id) REFERENCES vacancy (vacancy_id),
    resume_id integer NOT NULL,
    FOREIGN KEY (resume_id) REFERENCES resume (resume_id),
    description  text,
    unique (vacancy_id, resume_id)
);